Add depth anything sensory agent.
mbodiai/embodied-agents pull request #63
Opened 2024-07-29 00:52 UTC by nqyy

2024-08-02 19:11 UTC, sebbyjp commented on mbodied/agents/sense/depth_estimation_agent.py
> +    def act(self, image: Image, *args, api_name: str = "/depth", **kargs) -> Image:
fix kargs type please for here and below

2024-08-02 19:22 UTC, sebbyjp reviewed
add to pyproject.toml please
[tool.pytest.ini_options]
addopts = -m "not slow" -m "not network"
markers = [
    "slow: marks tests as slow (deselect with '\"-m "not slow\"')",
    "network": network calls (deselect with '\"-m "not network\"')",
]

2024-08-02 19:22 UTC, sebbyjp commented on mbodied/types/sense/scene.py
> +
```suggestion
class BBox2D(NamedTuple):
  x1: float
  y1: float
  x2: float
  y2: float
```
PixelCoords(NamedTuple):
  u: int
  v: int

BBox3D... etc

2024-08-03 01:24 UTC, sebbyjp requested changes
Waiting for the pytest.ini

2024-08-03 01:24 UTC, sebbyjp commented on mbodied/agents/sense/object_detection_agent.py
> +    def act(self, image: Image, objects: list[str] | str, *args, api_name: str = "/detect", **kwargs) -> Scene:
I thought we are calling this endpoint?

2024-08-06 02:50 UTC, nqyy commented
All resolved.

2024-08-06 14:33 UTC, sebbyjp approved these changes

2024-08-06 14:33 UTC, merged